/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
public class Helicopter extends javax.swing.JFrame implements SuperDefence {
    private MainController mainController;
    
    private int remainAmmoCount;
    private int defaultMissileCount;
    private int altitude;
    /**
     * Creates new form Helicopter
     */
    public Helicopter(MainController mainConroller) {
        initComponents();
        
        this.mainController=mainConroller;
        messageTextField.requestFocus();
        
        remainAmmoCount = 30;
        ammoCountSpinner.setValue(remainAmmoCount);
        
        defaultMissileCount = 5;
        
        setupAltitudeSlider();
        setupAltitudeListener();
        
    }
    
    private void setupAltitudeSlider() {
        altitudeSlider.setMinimum(0);
        altitudeSlider.setMaximum(5000);
        altitudeSlider.setMajorTickSpacing(1000);
        altitudeSlider.setMinorTickSpacing(100);
        altitudeSlider.setPaintTicks(true);
        altitudeSlider.setPaintLabels(true);
        altitudeSlider.setValue(0); // default ground level
    }
    
    private void setupAltitudeListener() {
        altitudeSlider.addChangeListener(e -> {
            altitude = altitudeSlider.getValue();
            
            if(altitude>=0 && altitude<1500) {
                viewTextArea.append("Laser fired at low altitude — high accuracy.\n");
            }
            if(altitude>=3500 && altitude<=5000) {
                viewTextArea.append("Laser fired at high altitude — reduced precision due to wind.\n");
            }
            altitudeLabel.setText("Altitude: "+altitude+"m");
            mainController.changeAltitude(altitude);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        viewScrollPane = new javax.swing.JScrollPane();
        viewTextArea = new javax.swing.JTextArea();
        messageTextField = new javax.swing.JTextField();
        sendButton = new javax.swing.JButton();
        laserOperationButton = new javax.swing.JButton();
        altitudeSlider = new javax.swing.JSlider();
        missileOperationButton = new javax.swing.JButton();
        shootButton = new javax.swing.JButton();
        areaClearedLabel = new javax.swing.JLabel();
        soldierCountLabel = new javax.swing.JLabel();
        ammoCountLabel = new javax.swing.JLabel();
        positionCheckBox = new javax.swing.JCheckBox();
        soldierCountSpinner = new javax.swing.JSpinner();
        ammoCountSpinner = new javax.swing.JSpinner();
        altitudeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        viewTextArea.setColumns(20);
        viewTextArea.setRows(5);
        viewScrollPane.setViewportView(viewTextArea);

        messageTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                messageTextFieldActionPerformed(evt);
            }
        });

        sendButton.setText("Send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });

        laserOperationButton.setText("Laser Operation");
        laserOperationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laserOperationButtonActionPerformed(evt);
            }
        });

        altitudeSlider.setOrientation(javax.swing.JSlider.VERTICAL);

        missileOperationButton.setText("Missile Operation");
        missileOperationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                missileOperationButtonActionPerformed(evt);
            }
        });

        shootButton.setText("Shoot");
        shootButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shootButtonActionPerformed(evt);
            }
        });

        areaClearedLabel.setText("Area Not Cleared");

        soldierCountLabel.setText("Soldier Count");

        ammoCountLabel.setText("Ammo Count");

        positionCheckBox.setText("Position");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(sendButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(shootButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(missileOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(laserOperationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(areaClearedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(positionCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soldierCountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ammoCountLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(soldierCountSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ammoCountSpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                                .addComponent(altitudeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(altitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soldierCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soldierCountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ammoCountSpinner)
                            .addComponent(ammoCountLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(positionCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(altitudeLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(areaClearedLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(shootButton)
                            .addComponent(missileOperationButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(laserOperationButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(messageTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sendButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(altitudeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        altitudeSlider.setBackground(new java.awt.Color(30, 30, 30));
        altitudeSlider.setForeground(new java.awt.Color(0,120,215));
        altitudeSlider.setPaintTicks(true);
        altitudeSlider.setPaintLabels(true);
        altitudeSlider.setMajorTickSpacing(20);
        altitudeSlider.setMinorTickSpacing(10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void messageTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_messageTextFieldActionPerformed
        sendButton.requestFocus();
        sendButton.doClick();
    }//GEN-LAST:event_messageTextFieldActionPerformed

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        String message = messageTextField.getText();
        mainController.displayMessagesFromHelicopter(message);
    }//GEN-LAST:event_sendButtonActionPerformed

    private void shootButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shootButtonActionPerformed
        String message="";
        if(remainAmmoCount<=0) {
            message = "Cannot shoot: No ammo remaining.";
            viewTextArea.append(message+"\n");
            mainController.notifyControlPanel(message);
        } else {
            remainAmmoCount--;
            updateAmmoCount(remainAmmoCount);
            
            message = "Heli: Fired a shot. Ammo remaining: ";
            // viewTextArea.append(message+""+remainAmmoCount+"\n");
            mainController.notifyObservers(message, remainAmmoCount);
            mainController.notifyControlPanel(message, remainAmmoCount);
        }
    }//GEN-LAST:event_shootButtonActionPerformed

    private void missileOperationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_missileOperationButtonActionPerformed
        String message="";
        if(defaultMissileCount<=0) {
            message = "Attempted missile fire but has no missiles left.";
            viewTextArea.append(message+"\n");
            mainController.notifyControlPanel(message);
        } else {
            defaultMissileCount--;
            
            message = "Heli: Launched a missile! Remaining missiles: ";
            // viewTextArea.append(message+""+defaultMissileCount+"\n");
            mainController.notifyObservers(message, defaultMissileCount);
            mainController.notifyControlPanel(message, defaultMissileCount);
        }
    }//GEN-LAST:event_missileOperationButtonActionPerformed

    private void laserOperationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laserOperationButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_laserOperationButtonActionPerformed

    
    @Override
    public void clearArea() {
        areaClearedLabel.setText("Area Cleared");
    }

    @Override
    public void defaultClearArea() {
        areaClearedLabel.setText("Area Not Cleared");
    }

    @Override
    public void updateInbox(String message) {
        viewTextArea.append(message+"\n");
    }

    @Override
    public void updateInbox(String message, int remain) {
        viewTextArea.append(message+""+remain+"\n");
    }
    
    
    
    private void updateAmmoCount(int remainAmmoCount) {
        ammoCountSpinner.setValue(remainAmmoCount);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel altitudeLabel;
    private javax.swing.JSlider altitudeSlider;
    private javax.swing.JLabel ammoCountLabel;
    private javax.swing.JSpinner ammoCountSpinner;
    private javax.swing.JLabel areaClearedLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton laserOperationButton;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JButton missileOperationButton;
    private javax.swing.JCheckBox positionCheckBox;
    private javax.swing.JButton sendButton;
    private javax.swing.JButton shootButton;
    private javax.swing.JLabel soldierCountLabel;
    private javax.swing.JSpinner soldierCountSpinner;
    private javax.swing.JScrollPane viewScrollPane;
    private javax.swing.JTextArea viewTextArea;
    // End of variables declaration//GEN-END:variables
}
